const kurlyDB =[
    {
        src:'images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'새콤달콤한 여름맛 간식',
        price:5500,
        sale:20,
        review:18,
    },{
        src: 'images/kurly_003.jpg',
        name: '[농심] 꿀꽈배기',
        summary: '달콤하고 고소한 전통 과자',
        price: 1500,
        sale: 10,
        review: 321,
    },
    {
        src: 'images/kurly_004.jpg',
        name: '[오리온] 초코파이 정(情)',
        summary: '부드러운 마시멜로와 초코의 조화',
        price: 3980,
        sale: 15,
        review: 212,
    },
    {
        src: 'images/kurly_005.jpg',
        name: '[빙그레] 바나나맛 우유',
        summary: '부드럽고 달콤한 국민 간식',
        price: 1200,
        sale: 0,
        review: 980,
    },
    {
        src: 'images/kurly_006.jpg',
        name: '[삼립] 호빵 (단팥)',
        summary: '따뜻하고 달콤한 겨울 간식',
        price: 2200,
        sale: 5,
        review: 76,
    },
    {
        src: 'images/kurly_007.jpg',
        name: '[팔도] 비빔면',
        summary: '매콤달콤한 여름철 별미',
        price: 950,
        sale: 8,
        review: 543,
    },
    {
        src: 'images/kurly_008.jpg',
        name: '[CJ] 햇반 컵반 불고기덮밥',
        summary: '간편하게 즐기는 한 끼 식사',
        price: 3900,
        sale: 12,
        review: 127,
    },
    {
        src: 'images/kurly_009.jpg',
        name: '[롯데] 몽쉘 크림케이크',
        summary: '촉촉하고 부드러운 디저트',
        price: 3000,
        sale: 10,
        review: 412,
    },
    {
        src: 'images/kurly_010.jpg',
        name: '[동원] 리챔 오리지널',
        summary: '든든하고 짭짤한 반찬',
        price: 4200,
        sale: 13,
        review: 234,
    },
    {
        src: 'images/kurly_011.jpg',
        name: '[서울우유] 흰우유 1L',
        summary: '신선하고 고소한 맛',
        price: 2500,
        sale: 5,
        review: 199,
    },
    {
        src: 'images/kurly_012.jpg',
        name: '[청정원] 고추장불고기 양념',
        summary: '요리 초보도 쉽게 만드는 불고기',
        price: 3300,
        sale: 18,
        review: 145,
    },
    
]